# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_alphabet', models.CharField(max_length=10)),
                ('car_number', models.CharField(max_length=10)),
                ('car_cprovince', models.CharField(max_length=10)),
                ('car_type', models.CharField(max_length=10)),
                ('is_tro', models.BooleanField(default=False)),
                ('is_insure', models.BooleanField(default=False)),
                ('is_paytax', models.BooleanField(default=False)),
                ('is_special', models.BooleanField(default=False)),
                ('is_sms', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created car')),
                ('expire_date', models.DateTimeField(verbose_name='date expire tax')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date update data')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('addr', models.CharField(max_length=45)),
                ('soi', models.CharField(blank=True, max_length=200)),
                ('road', models.CharField(blank=True, max_length=200)),
                ('moo', models.CharField(blank=True, max_length=10)),
                ('tumbon', models.CharField(max_length=200)),
                ('amphur', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=10)),
                ('tel', models.CharField(blank=True, max_length=45)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created customer')),
            ],
        ),
        migrations.CreateModel(
            name='MailHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created mail')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.Car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.Customer'),
        ),
    ]
