# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_cprovince',
            new_name='car_province',
        ),
    ]
